-- 1
DECLARE 
    NUMBER_MAX NUMBER(10) := 0;
    V_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    SELECT MAX(DEPARTMENT_ID) INTO NUMBER_MAX FROM DEPARTMENTS;
    V_NAME := 'EDUCATION';
    NUMBER_MAX := NUMBER_MAX + 10;

    INSERT INTO DEPARTMENTS VALUES(NUMBER_MAX, V_NAME, null, null);

    DBMS_OUTPUT.PUT_LINE('Maksymalny numer departamentu wynosi ' || NUMBER_MAX)
END;


-- 2
DECLARE 
    NUMBER_MAX NUMBER(10) := 0;
    V_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
    V_LOCATION_ID DEPARTMENTS.LOCATION_ID%TYPE
BEGIN
    SELECT MAX(DEPARTMENT_ID) INTO NUMBER_MAX FROM DEPARTMENTS;
    V_NAME := 'EDUCATION';
    NUMBER_MAX := NUMBER_MAX + 10;
    V_LOCATION_ID := 3000;

    INSERT INTO DEPARTMENTS VALUES(NUMBER_MAX, V_NAME, null, null);
    UPDATE DEPARTMENTS SET LOCATION_ID = V_LOCATION_ID WHERE DEPARTMENT_ID = NUMBER_MAX;

    DBMS_OUTPUT.PUT_LINE('Maksymalny numer departamentu wynosi ' || NUMBER_MAX)
END;


-- 3
CREATE TABLE NOWA
(
    COL1 VARCHAR(30)
);


DECLARE
    i NUMBER(4) := 1;
BEGIN
    WHILE i <= 10
        LOOP
            IF i <> 4 AND i <> 6 THEN
                INSERT INTO NOWA (COL1) VALUES (TO_CHAR(i));
            END IF;
            i := i + 1;
        END LOOP;
END;


-- 4
DECLARE
    V_COUNTRY_REC COUNTRIES%ROWTYPE;
    CURSOR C IS SELECT * FROM COUNTRIES WHERE COUNTRY_ID = 'CA';
BEGIN
    OPEN C;
    FETCH C INTO V_COUNTRY_REC;
    CLOSE C;
    DBMS_OUTPUT.PUT_LINE('Country name: ' || V_COUNTRY_REC.COUNTRY_NAME || ', region code: ' || V_COUNTRY_REC.REGION_ID);
END;


-- 5
DECLARE
    V_DEPARTMENT DEPARTMENTS%ROWTYPE;
BEGIN
    FOR i IN 1..10
        LOOP
            SELECT * INTO V_DEPARTMENT FROM DEPARTMENTS WHERE DEPARTMENT_ID = i * 10;
            DBMS_OUTPUT.PUT_LINE('Department id: ' || V_DEPARTMENT.DEPARTMENT_ID || ', department name: ' || V_DEPARTMENT.DEPARTMENT_NAME);
        END LOOP;
END;


-- 6
DECLARE
    V_DEPARTMENT DEPARTMENTS%ROWTYPE;
BEGIN  
    FOR i IN 1..10
        LOOP
            SELECT * INTO V_DEPARTMENT FROM DEPARTMENTS WHERE DEPARTMENT_ID = i * 10;
            DBMS_OUTPUT.PUT_LINE('Department id: ' 
                || V_DEPARTMENT.DEPARTMENT_ID 
                || ', department name: ' 
                || V_DEPARTMENT.DEPARTMENT_NAME
                || ', department manager_id'
                || V_DEPARTMENT.MANAGER_ID
                || ', department location_id'
                || V_DEPARTMENT.LOCATION_ID);
        END LOOP;
END;


-- 7
DECLARE
    CURSOR C IS SELECT * FROM EMP WHERE DEPARTMENT_ID = '50';